name: iris
functions:
- url: /User/repos/demo-xgb-project/src/iris.yaml
  name: xgb
- url: /User/repos/functions/xgb_serving/xgb_serving.ipynb
  name: serving
workflows:
- name: main
  path: /User/repos/demo-xgb-project/src/workflow.py
artifacts: []
