name: iris
functions:
- url: ./src/iris.yaml
  name: xgb
- url: https://raw.githubusercontent.com/yjb-ds/functions/v0.4.7/xgb_serving/xgb_serving.ipynb
  name: serving
workflows:
- name: main
  path: ./src/workflow.py
artifacts: []
